name: Deploy to Railway

on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli
        
      - name: Deploy to Railway
        run: |
          ls
          cd backend
          railway up --service theophania-final-project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}